  import { JobTypes } from './Jobs.types';

  export const JOBS: JobTypes[] = [
    {
      department: 'Applied Sciences',
      description: 'Design and implement automated systems for efficient operations.',
      id: 1,
      isRemote: false,
      location: 'Boston, MA',
      technologies: ['Automation Tools', 'PLC', 'SCADA'],
      title: 'Process Automation Engineer',
    },
    {
      department: 'Data Science & Analytics',
      description: 'Analyze and interpret complex data to provide actionable insights.',
      id: 2,
      isRemote: true,
      location: 'Remote',
      technologies: ['Python', 'R', 'TensorFlow', 'SQL'],
      title: 'Data Scientist',
    },
    {
      department: 'Electronics Development',
      description: 'Develop and optimize firmware for embedded systems.',
      id: 3,
      isRemote: false,
      location: 'Austin, TX',
      technologies: ['C', 'C++', 'Embedded Systems'],
      title: 'Firmware Engineer',
    },
    {
      department: 'Cloud Infrastructure',
      description: 'Design and manage scalable cloud infrastructure.',
      id: 4,
      isRemote: true,
      location: 'Seattle, WA',
      technologies: ['AWS', 'Azure', 'Google Cloud'],
      title: 'Cloud Architect',
    },
    {
      department: 'Software Engineering',
      description: 'Develop and maintain web applications across the stack.',
      id: 5,
      isRemote: true,
      location: 'New York, NY',
      technologies: ['JavaScript', 'React', 'Node.js', 'TypeScript'],
      title: 'Full Stack Developer',
    },
    {
      department: 'Artificial Intelligence',
      description: 'Develop and implement neural network models for AI solutions.',
      id: 6,
      isRemote: true,
      location: 'San Francisco, CA',
      technologies: ['Python', 'PyTorch', 'Keras'],
      title: 'Neural Networks Specialist',
    },
    {
      department: 'Data Science & Analytics',
      description: 'Create reports and dashboards to support data-driven decisions.',
      id: 7,
      isRemote: true,
      location: 'Remote',
      technologies: ['Tableau', 'Power BI', 'SQL'],
      title: 'Business Intelligence Analyst',
    },
    {
      department: 'Software Engineering',
      description: 'Design engaging user experiences for web and mobile platforms.',
      id: 8,
      isRemote: false,
      location: 'Los Angeles, CA',
      technologies: ['Figma', 'Adobe XD', 'Sketch'],
      title: 'UI/UX Designer',
    },
    {
      department: 'Artificial Intelligence',
      description: 'Build and deploy machine learning models into production.',
      id: 9,
      isRemote: true,
      location: 'Chicago, IL',
      technologies: ['Python', 'Scikit-Learn', 'TensorFlow'],
      title: 'Machine Learning Engineer',
    },
    {
      department: 'Cloud Infrastructure',
      description: 'Ensure seamless integration and delivery of software systems.',
      id: 10,
      isRemote: true,
      location: 'Denver, CO',
      technologies: ['Docker', 'Kubernetes', 'CI/CD'],
      title: 'DevOps Engineer',
    },
    {
      department: 'Electronics Development',
      description: 'Design and test electrical systems and components.',
      id: 11,
      isRemote: false,
      location: 'Houston, TX',
      technologies: ['Circuit Design', 'PCB Layout', 'VHDL'],
      title: 'Electrical Engineer',
    },
    {
      department: 'Data Science & Analytics',
      description: 'Interpret data and provide insights to support business decisions.',
      id: 12,
      isRemote: true,
      location: 'Miami, FL',
      technologies: ['SQL', 'Excel', 'Tableau'],
      title: 'Data Analyst',
    },
    {
      department: 'Software Engineering',
      description: 'Design and oversee the architecture of software systems.',
      id: 13,
      isRemote: true,
      location: 'San Diego, CA',
      technologies: ['Java', 'Microservices', 'AWS'],
      title: 'Software Architect',
    },
    {
      department: 'Software Engineering',
      description: 'Develop and execute tests to ensure software quality.',
      id: 14,
      isRemote: false,
      location: 'Portland, OR',
      technologies: ['Selenium', 'JUnit', 'TestRail'],
      title: 'Quality Assurance Engineer',
    },
    {
      department: 'Systems Integration',
      description: 'Integrate various systems to work seamlessly together.',
      id: 15,
      isRemote: true,
      location: 'Atlanta, GA',
      technologies: ['SOAP', 'REST', 'ETL'],
      title: 'Systems Integration Specialist',
    },
    {
      department: 'Systems Integration',
      description: 'Lead projects from conception to completion.',
      id: 16,
      isRemote: true,
      location: 'Dallas, TX',
      technologies: ['Agile', 'Scrum', 'JIRA'],
      title: 'Project Manager',
    },
    {
      department: 'Electronics Development',
      description: 'Design and analyze mechanical systems and components.',
      id: 17,
      isRemote: false,
      location: 'Detroit, MI',
      technologies: ['CAD', 'SolidWorks', 'ANSYS'],
      title: 'Mechanical Engineer',
    },
    {
      department: 'Artificial Intelligence',
      description: 'Conduct research to advance AI technologies.',
      id: 18,
      isRemote: true,
      location: 'Palo Alto, CA',
      technologies: ['Deep Learning', 'NLP', 'Computer Vision'],
      title: 'Artificial Intelligence Researcher',
    },
    {
      department: 'Cloud Infrastructure',
      description: 'Implement security measures for cloud-based systems.',
      id: 19,
      isRemote: true,
      location: 'Phoenix, AZ',
      technologies: ['IAM', 'Encryption', 'Firewalls'],
      title: 'Cloud Security Engineer',
    },
    {
      department: 'Applied Sciences',
      description: 'Analyze biological data using computational tools.',
      id: 20,
      isRemote: true,
      location: 'Raleigh, NC',
      technologies: ['R', 'Bioconductor', 'Genomics'],
      title: 'Bioinformatics Specialist',
    },
    {
      department: 'Software Engineering',
      description: 'Develop user-facing features for web applications.',
      id: 21,
      isRemote: true,
      location: 'Orlando, FL',
      technologies: ['HTML', 'CSS', 'JavaScript', 'React'],
      title: 'Frontend Developer',
    },
];