export const TECHNOLOGIES: string[] = [
    'ANSYS',
    'AWS',
    'Adobe XD',
    'Agile',
    'Automation Tools',
    'Azure',
    'Bioconductor',
    'C',
    'C++',
    'CAD',
    'CI/CD',
    'CSS',
    'Circuit Design',
    'Computer Vision',
    'Deep Learning',
    'Docker',
    'ETL',
    'Embedded Systems',
    'Encryption',
    'Excel',
    'Figma',
    'Firewalls',
    'Genomics',
    'Google Cloud',
    'HTML',
    'IAM',
    'JIRA',
    'JUnit',
    'Java',
    'JavaScript',
    'Keras',
    'Kubernetes',
    'Microservices',
    'NLP',
    'Node.js',
    'PCB Layout',
    'PLC',
    'Power BI',
    'PyTorch',
    'Python',
    'R',
    'REST',
    'React',
    'SCADA',
    'SOAP',
    'SQL',
    'Scikit-Learn',
    'Scrum',
    'Selenium',
    'Sketch',
    'SolidWorks',
    'Tableau',
    'TensorFlow',
    'TestRail',
    'TypeScript',
    'VHDL'
  ];